"""FIS schema: registry mirror, principals, leases

Revision ID: 953747624bf9
Revises:
Create Date: 2026-08-14 18:33:32.979105

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "953747624bf9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "g_nodes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("prev_alias", sa.String(), nullable=True),
        sa.Column(
            "base_class",
            sa.Enum(
                "TerminalAsset",
                "LeafTransactiveNode",
                "ConnectivityNode",
                "MarketMaker",
                "Logical",
                name="base_g_node_class",
            ),
            nullable=False,
        ),
        sa.Column("g_node_class", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "Pending",
                "Active",
                "Suspended",
                "PermanentlyDeactivated",
                name="g_node_status",
            ),
            nullable=False,
        ),
        sa.Column("position_point_id", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("mirrored_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_g_nodes_alias"), "g_nodes", ["alias"], unique=True)
    op.create_table(
        "leases",
        sa.Column("g_node_instance_id", sa.String(), nullable=False),
        sa.Column("principal_id", sa.String(), nullable=False),
        sa.Column("run", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Active", "Revoked", "Ended", name="g_node_instance_status"),
            nullable=False,
        ),
        sa.Column(
            "transport",
            sa.Enum("RabbitAmqp", "RabbitMqtt", name="g_node_instance_transport"),
            nullable=False,
        ),
        sa.Column("connected_at_unix_ms", sa.BigInteger(), nullable=False),
        sa.Column("revoked_at_unix_ms", sa.BigInteger(), nullable=True),
        sa.Column("connection_handle", sa.String(), nullable=True),
        sa.Column("observed_peer_address", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("g_node_instance_id"),
    )
    op.create_index(
        op.f("ix_leases_principal_id"), "leases", ["principal_id"], unique=False
    )
    op.create_index(op.f("ix_leases_run"), "leases", ["run"], unique=False)
    op.create_index(
        "uq_active_lease_per_principal_run",
        "leases",
        ["principal_id", "run"],
        unique=True,
        postgresql_where=sa.text("status = 'Active'"),
    )
    op.create_table(
        "principals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "kind", sa.Enum("GNode", "Service", name="principal_kind"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("Active", "Suspended", name="principal_status"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("principals")
    op.drop_index(
        "uq_active_lease_per_principal_run",
        table_name="leases",
        postgresql_where=sa.text("status = 'Active'"),
    )
    op.drop_index(op.f("ix_leases_run"), table_name="leases")
    op.drop_index(op.f("ix_leases_principal_id"), table_name="leases")
    op.drop_table("leases")
    op.drop_index(op.f("ix_g_nodes_alias"), table_name="g_nodes")
    op.drop_table("g_nodes")
    # ### end Alembic commands ###
